# Phi supports 'throw', 'try' and 'catch' which you can use to handle errors.

try {
    int x = 5 / 0
} catch (zeroDivisionError) {
	output("Oh no!")
}

# Instead of halting the program showing the error messaged it will only print out 'Oh no!' to the console


