import debug

debug.log(43 + 2)

debug.warning("This is unstable")

debug.error("An error occured")

